//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newDBClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class algorithmData
    {
        public int ID { get; set; }
        public string Maxx { get; set; }
        public string maxy { get; set; }
        public string maxz { get; set; }
        public string weightx { get; set; }
        public string weightSpeed { get; set; }
        public string maxSpeed { get; set; }
        public string weighty { get; set; }
        public string weightz { get; set; }
        public string stdDev { get; set; }
        public string average { get; set; }
    }
}
