//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newDBClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip
    {
        public int ID { get; set; }
        public Nullable<int> userID { get; set; }
        public string tripDate { get; set; }
        public string startTime { get; set; }
        public string score { get; set; }
    
        public virtual user user { get; set; }
    }
}
