//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace driveStatsServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class factor
    {
        public Nullable<float> maxXFactor { get; set; }
        public Nullable<float> maxYFactor { get; set; }
        public Nullable<float> maxZFactor { get; set; }
        public Nullable<float> speedFactor { get; set; }
        public Nullable<float> timeFactor { get; set; }
        public int ID { get; set; }
    }
}
