//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace driveStatsServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class friend
    {
        public int ID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> friendID { get; set; }
        public string currentStatus { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
