//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace driveStatsServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tripData
    {
        public int ID { get; set; }
        public Nullable<int> tripID { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public Nullable<double> speed { get; set; }
        public string recTime { get; set; }
        public Nullable<double> maxXAcelerometer { get; set; }
        public Nullable<double> maxYAcelerometer { get; set; }
        public Nullable<double> maxZAcelerometer { get; set; }
    
        public virtual trip trip { get; set; }
    }
}
