//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace graphs
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.trips = new HashSet<trip>();
        }
    
        public int ID { get; set; }
        public string email { get; set; }
        public string joinDate { get; set; }
        public Nullable<double> averageScore { get; set; }
    
        public virtual ICollection<trip> trips { get; set; }
    }
}
